services:
  - type: web
    name: ai-public-health-chatbot
    env: node
    root: backend
    buildCommand: npm ci
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true
